AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Interface endpoint for LDP accounts for S3 access

Parameters:
  Environment:
    Description: The environment in which the stack is deployed
    Type: String

Resources:
  CustomMapping:
    Type: Custom::Lookup
    Properties:
      ServiceToken: !Sub
        'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:liveservices-environment-mappings-lambda'
      environment: !Ref Environment
      region: !Ref AWS::Region
  EndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: A Security Group for S3 Interface endpoint
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !GetAtt CustomMapping.vpcCidr
          Description: Allowing the whole VPC to access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !GetAtt CustomMapping.vpcCidrAdditional
          Description: Allowing the whole VPC to access
      VpcId: !GetAtt CustomMapping.vpc
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
Outputs:
  EndpointSGId:
    Description: ID Of the S3 Interface endpoint Security Group
    Value: !GetAtt EndpointSG.GroupId
