---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation for deploying liveservices key pair import

Parameters:
  PublicKeyMaterial:
    Description: The Public Key Material Provided at deployment time to import the key
    Type: String
    NoEcho: true

Resources:
  LiveservicesKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: liveservices-key-pair
      PublicKeyMaterial: !Ref PublicKeyMaterial

Outputs:
  KeyPairId:
    Description: The ID of the Live Services Key pair
    Value: !GetAtt LiveservicesKeyPair.KeyPairId
  KeyFingerprint:
    Description: The fingerprint Live Services Key pair
    Value: !GetAtt LiveservicesKeyPair.KeyFingerprint
