AWSTemplateFormatVersion: '2010-09-09'
Description: >
  PrivateLink Consumer setup for banonprod-nonprod

Parameters:
  Environment:
    Description: The environment in which the stack is deployed
    Type: String
  PrivateLinkConnectionName:
    Description: The name of the PrivateLink Connection
    Type: String

Resources:
  CustomMapping:
    Type: Custom::Lookup
    Properties:
      ServiceToken: !Sub
        'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:liveservices-environment-mappings-lambda'
      environment: !Ref Environment
      region: !Ref AWS::Region
  EndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: A Security Group for banonprod-nonprod endpoint
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.89.184.0/22
          Description: Port 443 access to the VPC Endpoint
        - IpProtocol: tcp
          FromPort: 444
          ToPort: 444
          CidrIp: 10.89.184.0/22
          Description: Port 444 access to the VPC Endpoint
        - IpProtocol: tcp
          FromPort: 20101
          ToPort: 20101
          CidrIp: 10.89.184.0/22
          Description: Port 20101 access to the VPC Endpoint
        - IpProtocol: tcp
          FromPort: 10101
          ToPort: 10101
          CidrIp: 10.89.184.0/22
          Description: Port 10101 access to the VPC Endpoint
        - IpProtocol: tcp
          FromPort: 2222
          ToPort: 2222
          CidrIp: 10.89.184.0/22
          Description: Port 2222 access to the VPC Endpoint
      VpcId: !GetAtt CustomMapping.vpc
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
Outputs:
  EndpointSGId:
    Description: ID Of the PrivateLink endpoint Security Group
    Value: !GetAtt EndpointSG.GroupId
