{
 "title": "AWS - Private Link - NLB monitoring",
 "description": "Display health Metrics grafana dashboard for NLB private links",
 "tags": [
  "NLB",
  "AWS",
  "Cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product",
    "query": {
     "query": "label_values(cloudwatch_aws_network_elb_healthy_host_count_sum,product)\n\n"
    }
   },
   {
    "name": "environment",
    "query": {
     "query": "label_values(cloudwatch_aws_network_elb_healthy_host_count_sum{product=~\"$product\"} ,environment)\n"
    }
   },
   {
    "name": "loadbalancer",
    "query": {
     "query": "label_values(cloudwatch_aws_network_elb_healthy_host_count_sum{environment=~\"$environment\", product=~\"$product\"} ,load_balancer)"
    }
   },
   {
    "name": "targetgroup",
    "query": {
     "query": "label_values(cloudwatch_aws_network_elb_healthy_host_count_sum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}, target_group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NLB - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NLB - Active Flow Count",
   "type": "graph",
   "description": "Average active flow count on the NLB",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_active_flow_count_average{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{product}}-{{environment}}-{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - PeakPacketsPerSecond",
   "type": "graph",
   "description": "Peak Packet/sec  per load balancer",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(target_group) (cloudwatch_aws_network_elb_peak_packets_per_second_maximum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"})",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - Traget TLS Negotiation Errors",
   "type": "graph",
   "description": "The number of TLS connections initiated by the client that did not establish a session with the load balancer due to a TLS error.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_tlsn_negotiation_error_count_sum{product=\"$product\",environment=\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - Consumed LCU's",
   "type": "timeseries",
   "description": "The number of load balancer capacity units (LCU) used by your load balancer",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_consumed_lc_us_maximum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - PortAllocationErrorCount",
   "type": "timeseries",
   "description": "The total number of ephemeral port allocation errors during a client IP translation operation. A non-zero value indicates dropped client connections.",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_port_allocation_error_count_sum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - Client TLS Negotiation Errors",
   "type": "graph",
   "description": "The number of TLS connections initiated by the client that did not establish a session with the load balancer due to a TLS error.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_client_tlsn_negotiation_error_count_sum{product=\"$product\",environment=\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - Unhealthy hosts",
   "type": "bargauge",
   "description": "Number of unheathly host per target groups",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_un_healthy_host_count_maximum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\",target_group=~\"$targetgroup\"}/6",
     "legendFormat": "{{target_group}}"
    }
   ]
  },
  {
   "title": "NLB - counts",
   "type": "graph",
   "description": "Show active and new count",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_active_flow_count_average{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "Active flow Count - {{load_balancer}}"
    },
    {
     "expr": "cloudwatch_aws_network_elb_new_flow_count_sum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "New Flow Count - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB - Processed Bytes",
   "type": "graph",
   "description": "Data processed by the NLB",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_processed_bytes_sum{product=~\"$product\",environment=~\"$environment\",load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "Target Group details  - $targetgroup ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "targetgroup",
   "targets": [
    {}
   ]
  },
  {
   "title": "Hosts health",
   "type": "graph",
   "description": "Too many unhealthy hosts are bad, Keep your 5 a day up :P\nThis can indicate some of the server are not performing or communicating well with the NLB\n",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_aws_network_elb_healthy_host_count_maximum{environment=~\"$environment\",load_balancer=~\"$loadbalancer\",target_group=~\"$targetgroup\"}/6",
     "legendFormat": "Healthy Host {{target_group}}"
    },
    {
     "expr": "cloudwatch_aws_network_elb_un_healthy_host_count_maximum{environment=~\"$environment\",load_balancer=~\"$loadbalancer\",target_group=~\"$targetgroup\"}/6",
     "legendFormat": "Unheathy Host {{target_group}}"
    }
   ]
  }
 ]
}